target("tinyobj")
    set_kind("static")
    add_deps("c-ipc")
    add_files("tiny_obj_loader.cc")

-- target("finitediff")
--     set_kind("static")
--     add_deps("c-ipc")
--     add_headerfiles("finitediff.hpp")
--     add_files("finitediff.cpp")

target("test_gradient")
    add_deps("c-ipc", "tinyobj")
    add_files("gradient.cpp")
    add_packages("catch2")
    add_tests("default")

-- target("test_parallel")
--     add_deps("c-ipc")
--     add_files("parallel_test.cpp")
--     add_packages("catch2")